spring:
  main:
    web-application-type: none

odr:
  url: jdbc:postgresql://localhost:5432/odr
  username: postgres
  password: pgadmin
  driver-class-name: org.postgresql.Driver
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.connection.url: ${odr.url}
      hibernate.connection.username: ${odr.username}
      hibernate.connection.password: ${odr.password}
      hibernate.connection.autocommit: false
      hibernate.connection.isolation: TRANSACTION_REPEATABLE_READ
      hibernate.connection.pool_size: ${odr.hikari.maximum-pool-size}
      hibernate.connection.provider_disables_autocommit: true
      hibernate.temp.allow_jdbc_metadata_access: true
      hibernate.jdbc.lob.non_contextual_creation: true

gims:
  url: jdbc:postgresql://localhost:5432/second
  username: postgres
  password: pgadmin
  driver-class-name: org.postgresql.Driver
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.connection.url: ${gims.url}
      hibernate.connection.username: ${gims.username}
      hibernate.connection.password: ${gims.password}
      hibernate.connection.autocommit: false
      hibernate.connection.isolation: TRANSACTION_REPEATABLE_READ
      hibernate.connection.pool_size: ${gims.hikari.maximum-pool-size}
      hibernate.connection.provider_disables_autocommit: true
      hibernate.temp.allow_jdbc_metadata_access: true
      hibernate.jdbc.lob.non_contextual_creation: true

stdpro:
  mail:
    api-key: toto
    api-secret-key: toto